# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d17ffae6c14146d3fc478aa15636b9686b22a2fe76d60cbbc7a4ae65a86a1efd91b93b5a1762f527d21f329c800fdf823cbdad6396f6915b693783b21d0b610

test:
  secret_key_base: 4b621992fe5f1b06ab9940f35ec0519abc7a6dae64ff4311c19324aaba828ceccd8c3030d2d168d1220e9aaafeaaed3dab73d3478cc8be53bcc454aae0ae6a5b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
